version: "3"
services:
  node-1:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./conf/etcd-1.conf.yml:/etc/etcd.conf"
    ports:
      - 2001:2379
  node-2:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./conf/etcd-2.conf.yml:/etc/etcd.conf"
    ports:
      - 2002:2379
  node-3:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./conf/etcd-3.conf.yml:/etc/etcd.conf"
    ports:
      - 2003:2379
