version: '3'
services:
  node-1:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./etcd-1.conf.yml:/etc/etcd.conf"
  node-2:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./etcd-2.conf.yml:/etc/etcd.conf"
  node-3:
    image: quay.io/coreos/etcd:v3.3.12
    command:
      - etcd
      - --config-file
      - /etc/etcd.conf
    volumes:
      - "./etcd-3.conf.yml:/etc/etcd.conf"
