apiVersion: v1
kind: ServiceAccount
metadata:
  name: "operator"
  namespace: mboye
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "mboye-leader-election-demo"
  namespace: mboye
spec:
  replicas: 3
  selector:
    matchLabels:
      application: "mboye-leader-election-demo"
  template:
    metadata:
      labels:
        application: "mboye-leader-election-demo"
    spec:
      serviceAccountName: "operator"
      containers:
        - name: "leader-elector"
          image: googlecontainer/leader-elector:0.5
          args:
            - "--election=mboye-leader-election-demo"
            - "--http=localhost:4040"
            - "--election-namespace=mboye"
          ports:
            - containerPort: 4040
              protocol: TCP
        - name: "app"
          image: mboye/leader-election-app:v1
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: "mboye-leader-election-demo"
  name: "mboye-leader-election-demo"
  namespace: mboye
spec:
  selector:
    application: "mboye-leader-election-demo"
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "mboye-leader-election-demo"
  namespace: mboye
  labels:
    application: "leader-election-demo"
spec:
  rules:
    - host: "mboye-leader-election-demo.partner-solutions-test.zalan.do"
      http:
        paths:
          - backend:
              serviceName: "mboye-leader-election-demo"
              servicePort: 80
